plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

run {
    standardInput = System.in
    jvmArgs += [
        '--enable-native-access=ALL-UNNAMED',
        '--add-exports', 'javafx.graphics/com.sun.glass.ui=ALL-UNNAMED'
    ]
}

group 'com.scrum-lords-unanimous'
version '0.1'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.21.0'
    implementation 'org.fxmisc.richtext:richtextfx:0.11.3'
}

javafx {
    version = "24"
    modules = [ 'javafx.controls' ]
}

application {
    mainClass = 'Main'
}
